# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformInstaller@0
  displayName: 'TF_Install'
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  displayName: 'TF_Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'SPN-project01-927432'
    backendAzureRmResourceGroupName: 'S2-RG-CORE-project01'
    backendAzureRmStorageAccountName: 'coreproject01927432'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'main.tfstate'
- task: AzureKeyVault@2
  displayName: 'TF_KeyVault'
  inputs:
    azureSubscription: 'SPN-project01-927432'
    KeyVaultName: 'core-project01-kv927432'
    SecretsFilter: '*'
    RunAsPreJob: true
- task: TerraformTaskV3@3
  displayName: 'TF_Validate'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-out tfplan'
    environmentServiceNameAzureRM: 'SPN-project01-927432'
- task: TerraformTaskV3@3
  displayName: 'TF_Deploy'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: 'tfplan'
    environmentServiceNameAzureRM: 'SPN-project01-927432'
    